// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kozdfctghzkkexzhkeau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvemRmY3RnaHpra2V4emhrZWF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MjMwMTIsImV4cCI6MjA2MTM5OTAxMn0.oIX44F3nSJfneLq0J8-BdKhUJK8LM_WHRLhYWSwQq-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);